@OpenWFCsharp.Nas_Host = localhost:5120
@OpenWFCsharp.Nas_HostAddress = http://localhost:5120

### Connection test
GET {{OpenWFCsharp.Nas_HostAddress}}/
Host: {{OpenWFCsharp.Nas_Host}}
Connection: Close

### NAS - login
POST {{OpenWFCsharp.Nas_HostAddress}}/ac
Content-type: application/x-www-form-urlencoded
Host: {{OpenWFCsharp.Nas_Host}}
User-Agent: Nitro WiFi SDK/5.6
HTTP_X_GAMECD: VPYP
Connection: close

action=bG9naW4*&gsbrcd=&sdkver=MDA1MDA2&userid=MjAzNDE3NzA3OTU5Mg**&passwd=NjUx&bssid=MDBmMDc3Nzc3Nzc3&apinfo=MDA6MDAwMDAwMC0wMA**&gamecd=VlBZUA**&makercd=MDE*&unitcd=MA**&macadr=MDAwOWJmMTEyMjMz&lang=MDE*&birth=MDEwMQ**&devtime=MjMxMjE4MTIwNzAx&devname=bQBlAGwAbwBuAEQAUwA*

### NAS - SVCLOG
POST {{OpenWFCsharp.Nas_HostAddress}}/ac
Content-type: application/x-www-form-urlencoded
Host: {{OpenWFCsharp.Nas_Host}}
User-Agent: Nitro WiFi SDK/5.6
HTTP_X_GAMECD: VPYP
Connection: close

sdkver=MDA1MDA2&userid=MjAzNDE3NzA3OTU5Mg**&passwd=NjUx&bssid=MDBmMDc3Nzc3Nzc3&apinfo=MDA6MDAwMDAwMC0wMA**&gamecd=VlBZUA**&makercd=MDE*&unitcd=MA**&macadr=MDAwOWJmMTEyMjMz&lang=MDE*&birth=MDEwMQ**&devtime=MjMxMjE4MTIwNzAx&devname=bQBlAGwAbwBuAEQAUwA*&action=U1ZDTE9D&svc=OTAwMA**
