@OpenWFCsharp.Backend_Host = localhost:5120
@OpenWFCsharp.Backend_HostAddress = http://localhost:5120

### Connection test
GET {{OpenWFCsharp.Backend_HostAddress}}/
Host: {{OpenWFCsharp.Backend_Host}}
Connection: Close

### NAS - login
POST {{OpenWFCsharp.Backend_HostAddress}}/ac
Content-type: application/x-www-form-urlencoded
Host: {{OpenWFCsharp.Backend_Host}}
User-Agent: Nitro WiFi SDK/5.3
HTTP_X_GAMECD: B2KJ
Connection: close

action=bG9naW4*&gsbrcd=&sdkver=MDA1MDAz&userid=Nzg4MTk4NjAyOTYzMQ**&passwd=Mjk3&bssid=MDBmMDFhMmIzYzRk&apinfo=MDI6MDAwMDAwMC0wMA**&gamecd=QjJLSg**&makercd=SEY*&unitcd=MA**&macadr=MDAxNjU2ODMzMWY5&lang=MDU*&birth=MDcwYw**&devtime=MTQwNDI5MTMxMDA1&devname=cABsAGUAbwBuAGUAeAA*

### NAS - SVCLOG
POST {{OpenWFCsharp.Backend_HostAddress}}/ac
Content-type: application/x-www-form-urlencoded
Host: {{OpenWFCsharp.Backend_Host}}
User-Agent: Nitro WiFi SDK/5.3
HTTP_X_GAMECD: B2KJ
Connection: close

sdkver=MDA1MDAz&userid=Nzg4MTk4NjAyOTYzMQ**&passwd=Mjk3&bssid=MDBmMDFhMmIzYzRk&apinfo=MDI6MDAwMDAwMC0wMA**&gamecd=QjJLSg**&makercd=SEY*&unitcd=MA**&macadr=MDAxNjU2ODMzMWY5&lang=MDU*&birth=MDcwYw**&devtime=MTQwNDI5MTMxMDA4&devname=cABsAGUAbwBuAGUAeAA*&action=U1ZDTE9D&svc=OTAwMA**

### DSL1 - count
POST {{OpenWFCsharp.Backend_HostAddress}}/download
Host: {{OpenWFCsharp.Backend_Host}}
User-Agent: Nitro WiFi SDK/5.3
Content-Type: application/x-www-form-urlencoded

gamecd=QjJLSg%2A%2A&rhgamecd=QjJLSg%2A%2A&passwd=a0ZFYXBRV0NNZFBKbUs3SA%2A%2A&token=SUFUVTk5SXlETWozWkR1UnhpUWZWWTFOemF6ZktWK3VCUzdEWjNrREwxZ3hJMFpLenNCQkRKMmFWZUNsbk90ZjlSQXkwVFprTlV6cmNTVy9DT0hMeHc9PQ%2A%2A&userid=Nzg4MTk4NjAyOTYzMQ%2A%2A&macadr=MDAxNjU2ODMzMWY5&action=Y291bnQ%2A&apinfo=MDI6MDAwMDAwMC0wMA%2A%2A

### DSL1 - list
POST {{OpenWFCsharp.Backend_HostAddress}}/download
Host: {{OpenWFCsharp.Backend_Host}}
User-Agent: Nitro WiFi SDK/5.3
Content-Type: application/x-www-form-urlencoded

gamecd=QjJLSg%2A%2A&rhgamecd=QjJLSg%2A%2A&passwd=a0ZFYXBRV0NNZFBKbUs3SA%2A%2A&token=SUFUVTk5SXlETWozWkR1UnhpUWZWWTFOemF6ZktWK3VCUzdEWjNrREwxZ3hJMFpLenNCQkRKMmFWZUNsbk90ZjlSQXkwVFprTlV6cmNTVy9DT0hMeHc9PQ%2A%2A&userid=Nzg4MTk4NjAyOTYzMQ%2A%2A&macadr=MDAxNjU2ODMzMWY5&action=bGlzdA%2A%2A&apinfo=MDI6MDAwMDAwMC0wMA%2A%2A&offset=MA%2A%2A&num=MQ%2A%2A

### DSL1 - contents
POST {{OpenWFCsharp.Backend_HostAddress}}/download
Host: {{OpenWFCsharp.Backend_Host}}
User-Agent: Nitro WiFi SDK/5.3
Content-Type: application/x-www-form-urlencoded

gamecd=QjJLSg%2A%2A&rhgamecd=QjJLSg%2A%2A&passwd=a0ZFYXBRV0NNZFBKbUs3SA%2A%2A&token=SUFUVTk5SXlETWozWkR1UnhpUWZWWTFOemF6ZktWK3VCUzdEWjNrREwxZ3hJMFpLenNCQkRKMmFWZUNsbk90ZjlSQXkwVFprTlV6cmNTVy9DT0hMeHc9PQ%2A%2A&userid=Nzg4MTk4NjAyOTYzMQ%2A%2A&macadr=MDAxNjU2ODMzMWY5&action=Y29udGVudHM%2A&apinfo=MDI6MDAwMDAwMC0wMA%2A%2A&contents=ZGlzdHJpYnV0aW9uMTEwNjA5LmJpbg%2A%2A

###